/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  ActionsApi,
  DomainsApi,
  NotificationsApi,
  V1Api,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { GoDaddyCustom } from "./client-custom";

export class GoDaddy extends GoDaddyCustom {
  readonly actions: ActionsApi;
  readonly domains: DomainsApi;
  readonly notifications: NotificationsApi;
  readonly v1: V1Api;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.actions = new ActionsApi(configuration);
    this.domains = new DomainsApi(configuration);
    this.notifications = new NotificationsApi(configuration);
    this.v1 = new V1Api(configuration);
  }

}
