/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ErrorField } from './error-field';

/**
 * 
 * @export
 * @interface ActionReason
 */
export interface ActionReason {
    /**
     * Short identifier, suitable for indicating the reason for the current status and how to handle within client code
     * @type {string}
     * @memberof ActionReason
     */
    'code': string;
    /**
     * List of the specific fields, and the errors found with their contents
     * @type {Array<ErrorField>}
     * @memberof ActionReason
     */
    'fields'?: Array<ErrorField>;
    /**
     * Human-readable, English description of the code
     * @type {string}
     * @memberof ActionReason
     */
    'message'?: string;
}

