/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ConsentV2
 */
export interface ConsentV2 {
    /**
     * Timestamp indicating when the end-user consented to these legal agreements
     * @type {string}
     * @memberof ConsentV2
     */
    'agreedAt': string;
    /**
     * Originating client IP address of the end-user\'s computer when they consented to these legal agreements
     * @type {string}
     * @memberof ConsentV2
     */
    'agreedBy': string;
    /**
     * Unique identifiers of the legal agreements to which the end-user has agreed, as returned from the/domains/agreements endpoint
     * @type {Array<string>}
     * @memberof ConsentV2
     */
    'agreementKeys': Array<string>;
    /**
     * The trademark claim token, only needed if the domain has an active trademark claim
     * @type {string}
     * @memberof ConsentV2
     */
    'claimToken'?: string;
    /**
     * Currency in which the `price` is listed
     * @type {string}
     * @memberof ConsentV2
     */
    'currency': string;
    /**
     * Price of the domain excluding taxes or fees. Please use GET /v1/domains/available to retrieve the price and currency for the domain
     * @type {number}
     * @memberof ConsentV2
     */
    'price': number;
    /**
     * Only required for hosted registrar if domain is premium. If true indicates that the `price` and `currency` listed are the registry premium price and currency for the domain
     * @type {boolean}
     * @memberof ConsentV2
     */
    'registryPremiumPricing'?: boolean;
}

