/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ConsentRenew
 */
export interface ConsentRenew {
    /**
     * Timestamp indicating when the end-user consented to these legal agreements
     * @type {string}
     * @memberof ConsentRenew
     */
    'agreedAt': string;
    /**
     * Originating client IP address of the end-user\'s computer when they consented to these legal agreements
     * @type {string}
     * @memberof ConsentRenew
     */
    'agreedBy': string;
    /**
     * Currency in which the `price` is listed
     * @type {string}
     * @memberof ConsentRenew
     */
    'currency': string;
    /**
     * Price of the domain excluding taxes or fees. Please use GET /v2/customers/{customerId}/domains/{domain} to retrieve the renewal price and currency for the domain
     * @type {number}
     * @memberof ConsentRenew
     */
    'price': number;
    /**
     * Only required for hosted registrar if domain is premium. If true indicates that the `price` and `currency` listed are the registry premium price and currency for the domain
     * @type {boolean}
     * @memberof ConsentRenew
     */
    'registryPremiumPricing'?: boolean;
}

