/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ConsentDomainUpdate
 */
export interface ConsentDomainUpdate {
    /**
     * Timestamp indicating when the end-user consented to these agreements
     * @type {string}
     * @memberof ConsentDomainUpdate
     */
    'agreedAt': string;
    /**
     * Originating client IP address of the end-user\'s computer when they consented to the agreements
     * @type {string}
     * @memberof ConsentDomainUpdate
     */
    'agreedBy': string;
    /**
     * Unique identifiers of the agreements to which the end-user has agreed, as required by the elements being updated<br/><ul><li><strong style=\'margin-left: 12px;\'>EXPOSE_WHOIS</strong> - Required when the exposeWhois field is updated to true</li></ul>
     * @type {Array<string>}
     * @memberof ConsentDomainUpdate
     */
    'agreementKeys': Array<ConsentDomainUpdateAgreementKeysEnum>;
}

type ConsentDomainUpdateAgreementKeysEnum = 'EXPOSE_WHOIS'


