/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Consent
 */
export interface Consent {
    /**
     * Timestamp indicating when the end-user consented to these legal agreements
     * @type {string}
     * @memberof Consent
     */
    'agreedAt': string;
    /**
     * Originating client IP address of the end-user\'s computer when they consented to these legal agreements
     * @type {string}
     * @memberof Consent
     */
    'agreedBy': string;
    /**
     * Unique identifiers of the legal agreements to which the end-user has agreed, as returned from the/domains/agreements endpoint
     * @type {Array<string>}
     * @memberof Consent
     */
    'agreementKeys': Array<string>;
}

