/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ConsentRedemption
 */
export interface ConsentRedemption {
    /**
     * Timestamp indicating when the end-user consented to these legal agreements
     * @type {string}
     * @memberof ConsentRedemption
     */
    'agreedAt': string;
    /**
     * Originating client IP address of the end-user\'s computer when they consented to these legal agreements
     * @type {string}
     * @memberof ConsentRedemption
     */
    'agreedBy': string;
    /**
     * Currency in which the `price` and `fee` are listed
     * @type {string}
     * @memberof ConsentRedemption
     */
    'currency': string;
    /**
     * Fee charged for the domain redemption. Please use GET /v2/customers/{customerId}/domains/{domain} to retrieve the redemption fee and currency for the domain
     * @type {number}
     * @memberof ConsentRedemption
     */
    'fee': number;
    /**
     * Price for the domain renewal (if domain renewal required for redemption). Please use GET /v2/customers/{customerId}/domains/{domain} to retrieve the redemption price and currency for the domain
     * @type {number}
     * @memberof ConsentRedemption
     */
    'price': number;
}

