/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';

/**
 * 
 * @export
 * @interface Contact
 */
export interface Contact {
    /**
     * 
     * @type {Address}
     * @memberof Contact
     */
    'addressMailing': Address;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    'fax'?: string;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    'jobTitle'?: string;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    'nameFirst': string;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    'nameLast': string;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    'nameMiddle'?: string;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    'organization'?: string;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    'phone': string;
}

