/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';

/**
 * 
 * @export
 * @interface ContactDomain
 */
export interface ContactDomain {
    /**
     * Timestamp indicating when the contact was created
     * @type {string}
     * @memberof ContactDomain
     */
    '_createdAt'?: string;
    /**
     * Flag indicating if the contact has been logically deleted in the system
     * @type {boolean}
     * @memberof ContactDomain
     */
    '_deleted'?: boolean;
    /**
     * Timestamp indicating when the contact was last modified
     * @type {string}
     * @memberof ContactDomain
     */
    '_modifiedAt'?: string;
    /**
     * The current revision number of the contact.
     * @type {number}
     * @memberof ContactDomain
     */
    '_revision'?: number;
    /**
     * 
     * @type {Address}
     * @memberof ContactDomain
     */
    'addressMailing': Address;
    /**
     * Unique identifier for this Contact
     * @type {string}
     * @memberof ContactDomain
     */
    'contactId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactDomain
     */
    'email': string;
    /**
     * The encoding of the contact data<br/><ul><li><strong style=\'margin-left: 12px;\'>ASCII</strong> - Data contains only ASCII characters that are not region or language specific</li><li><strong style=\'margin-left: 12px;\'>UTF-8</strong> - Data contains characters that are specific to a region or language</li></ul>
     * @type {string}
     * @memberof ContactDomain
     */
    'encoding'?: ContactDomainEncodingEnum;
    /**
     * Whether or not the contact details should be shown in the WHOIS
     * @type {boolean}
     * @memberof ContactDomain
     */
    'exposeWhois': boolean;
    /**
     * 
     * @type {string}
     * @memberof ContactDomain
     */
    'fax'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactDomain
     */
    'jobTitle'?: string;
    /**
     * The contact eligibility data fields as specified by GET /v2/customers/{customerId}/domains/contacts/schema/{tld}
     * @type {object}
     * @memberof ContactDomain
     */
    'metadata'?: object;
    /**
     * 
     * @type {string}
     * @memberof ContactDomain
     */
    'nameFirst': string;
    /**
     * 
     * @type {string}
     * @memberof ContactDomain
     */
    'nameLast': string;
    /**
     * 
     * @type {string}
     * @memberof ContactDomain
     */
    'nameMiddle'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactDomain
     */
    'organization'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactDomain
     */
    'phone': string;
    /**
     * The tlds that this contact can be assigned to
     * @type {Array<string>}
     * @memberof ContactDomain
     */
    'tlds'?: Array<string>;
}

type ContactDomainEncodingEnum = 'ASCII' | 'UTF-8'


