/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';

/**
 * 
 * @export
 * @interface ContactDomainCreate
 */
export interface ContactDomainCreate {
    /**
     * 
     * @type {Address}
     * @memberof ContactDomainCreate
     */
    'addressMailing': Address;
    /**
     * 
     * @type {string}
     * @memberof ContactDomainCreate
     */
    'email': string;
    /**
     * The encoding of the contact data<br/><ul><li><strong style=\'margin-left: 12px;\'>ASCII</strong> - Data contains only ASCII characters that are not region or language specific</li><li><strong style=\'margin-left: 12px;\'>UTF-8</strong> - Data contains characters that are specific to a region or language</li></ul>
     * @type {string}
     * @memberof ContactDomainCreate
     */
    'encoding': ContactDomainCreateEncodingEnum;
    /**
     * 
     * @type {string}
     * @memberof ContactDomainCreate
     */
    'fax'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactDomainCreate
     */
    'jobTitle'?: string;
    /**
     * The contact eligibility data fields as specified by GET /v2/customers/{customerId}/domains/contacts/schema/{tld}
     * @type {object}
     * @memberof ContactDomainCreate
     */
    'metadata'?: object;
    /**
     * 
     * @type {string}
     * @memberof ContactDomainCreate
     */
    'nameFirst': string;
    /**
     * 
     * @type {string}
     * @memberof ContactDomainCreate
     */
    'nameLast': string;
    /**
     * 
     * @type {string}
     * @memberof ContactDomainCreate
     */
    'nameMiddle'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactDomainCreate
     */
    'organization'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactDomainCreate
     */
    'phone': string;
}

type ContactDomainCreateEncodingEnum = 'ASCII' | 'UTF-8'


