/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DNSRecord
 */
export interface DNSRecord {
    /**
     * 
     * @type {string}
     * @memberof DNSRecord
     */
    'data': string;
    /**
     * 
     * @type {string}
     * @memberof DNSRecord
     */
    'name': string;
    /**
     * Service port (SRV only)
     * @type {number}
     * @memberof DNSRecord
     */
    'port'?: number;
    /**
     * Record priority (MX and SRV only)
     * @type {number}
     * @memberof DNSRecord
     */
    'priority'?: number;
    /**
     * Service protocol (SRV only)
     * @type {string}
     * @memberof DNSRecord
     */
    'protocol'?: string;
    /**
     * Service type (SRV only)
     * @type {string}
     * @memberof DNSRecord
     */
    'service'?: string;
    /**
     * 
     * @type {number}
     * @memberof DNSRecord
     */
    'ttl'?: number;
    /**
     * 
     * @type {string}
     * @memberof DNSRecord
     */
    'type': DNSRecordTypeEnum;
    /**
     * Record weight (SRV only)
     * @type {number}
     * @memberof DNSRecord
     */
    'weight'?: number;
}

type DNSRecordTypeEnum = 'A' | 'AAAA' | 'CNAME' | 'MX' | 'NS' | 'SOA' | 'SRV' | 'TXT'


