/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DomainAvailableResponse
 */
export interface DomainAvailableResponse {
    /**
     * Whether or not the domain name is available
     * @type {boolean}
     * @memberof DomainAvailableResponse
     */
    'available': boolean;
    /**
     * Currency in which the `price` is listed. Only returned if tld is offered
     * @type {string}
     * @memberof DomainAvailableResponse
     */
    'currency'?: string;
    /**
     * Whether or not the `available` answer has been definitively verified with the registry
     * @type {boolean}
     * @memberof DomainAvailableResponse
     */
    'definitive': boolean;
    /**
     * Domain name
     * @type {string}
     * @memberof DomainAvailableResponse
     */
    'domain': string;
    /**
     * Number of years included in the price. Only returned if tld is offered
     * @type {number}
     * @memberof DomainAvailableResponse
     */
    'period'?: number;
    /**
     * Price of the domain excluding taxes or fees. Only returned if tld is offered
     * @type {number}
     * @memberof DomainAvailableResponse
     */
    'price'?: number;
}

