/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ContactDomain } from './contact-domain';

/**
 * 
 * @export
 * @interface DomainContactsV2
 */
export interface DomainContactsV2 {
    /**
     * 
     * @type {ContactDomain}
     * @memberof DomainContactsV2
     */
    'admin'?: ContactDomain;
    /**
     * 
     * @type {ContactDomain}
     * @memberof DomainContactsV2
     */
    'billing'?: ContactDomain;
    /**
     * 
     * @type {ContactDomain}
     * @memberof DomainContactsV2
     */
    'registrant'?: ContactDomain;
    /**
     * 
     * @type {ContactDomain}
     * @memberof DomainContactsV2
     */
    'tech'?: ContactDomain;
}

