/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DomainForwardingMask } from './domain-forwarding-mask';

/**
 * 
 * @export
 * @interface DomainForwardingCreate
 */
export interface DomainForwardingCreate {
    /**
     * 
     * @type {DomainForwardingMask}
     * @memberof DomainForwardingCreate
     */
    'mask'?: DomainForwardingMask;
    /**
     * The type of fowarding to implement<br/><ul><li><strong style=\'margin-left: 12px;\'>MASKED</strong> - Prevents the forwarded domain or subdomain URL from displaying in the browser\'s address bar.</li><li><strong style=\'margin-left: 12px;\'>REDIRECT_PERMANENT*</strong> - Redirects to the url you specified in the forwardTo field using a `301 Moved Permanently` HTTP response. The HTTP 301 response code tells user-agents (including search engines) that the location has permanently moved.</li><li><strong style=\'margin-left: 12px;\'>REDIRECT_TEMPORARY</strong> - Redirects to the url you specified in the forwardTo field using a `302 Found` HTTP response. The HTTP 302 response code tells user-agents (including search engines) that the location has temporarily moved.</li></ul>
     * @type {string}
     * @memberof DomainForwardingCreate
     */
    'type': DomainForwardingCreateTypeEnum;
    /**
     * Forwards http(s) traffic to this destination url (ex. http://www.somedomain.com/)
     * @type {string}
     * @memberof DomainForwardingCreate
     */
    'url': string;
}

type DomainForwardingCreateTypeEnum = 'MASKED' | 'REDIRECT_PERMANENT' | 'REDIRECT_TEMPORARY'


