/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DomainAvailableResponse } from './domain-available-response';

/**
 * 
 * @export
 * @interface DomainAvailableBulk
 */
export interface DomainAvailableBulk {
    /**
     * Domain available response array
     * @type {Array<DomainAvailableResponse>}
     * @memberof DomainAvailableBulk
     */
    'domains': Array<DomainAvailableResponse>;
}

