/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DomainAvailableError
 */
export interface DomainAvailableError {
    /**
     * Short identifier for the error, suitable for indicating the specific error within client code
     * @type {string}
     * @memberof DomainAvailableError
     */
    'code': string;
    /**
     * Domain name
     * @type {string}
     * @memberof DomainAvailableError
     */
    'domain': string;
    /**
     * Human-readable, English description of the error
     * @type {string}
     * @memberof DomainAvailableError
     */
    'message'?: string;
    /**
     * <ul> <li style=\'margin-left: 12px;\'>JSONPath referring to a field containing an error</li> <strong style=\'margin-left: 12px;\'>OR</strong> <li style=\'margin-left: 12px;\'>JSONPath referring to a field that refers to an object containing an error, with more detail in `pathRelated`</li> </ul>
     * @type {string}
     * @memberof DomainAvailableError
     */
    'path': string;
    /**
     * HTTP status code that would return for a single check
     * @type {number}
     * @memberof DomainAvailableError
     */
    'status': number;
}

