/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DomainPurchaseResponse
 */
export interface DomainPurchaseResponse {
    /**
     * Currency in which the `total` is listed
     * @type {string}
     * @memberof DomainPurchaseResponse
     */
    'currency'?: string;
    /**
     * Number items included in the order
     * @type {number}
     * @memberof DomainPurchaseResponse
     */
    'itemCount': number;
    /**
     * Unique identifier of the order processed to purchase the domain
     * @type {number}
     * @memberof DomainPurchaseResponse
     */
    'orderId': number;
    /**
     * Total cost of the domain and any selected add-ons
     * @type {number}
     * @memberof DomainPurchaseResponse
     */
    'total': number;
}

