/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DomainForwardingMask
 */
export interface DomainForwardingMask {
    /**
     * Displays at the top of the browser window and in search results.
     * @type {string}
     * @memberof DomainForwardingMask
     */
    'title'?: string;
    /**
     * A short description of your website to display in search engine results.
     * @type {string}
     * @memberof DomainForwardingMask
     */
    'description'?: string;
    /**
     * A list of comma-separated keywords that describes the content and purpose of your website.
     * @type {string}
     * @memberof DomainForwardingMask
     */
    'keywords'?: string;
}

