/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DomainAvailableError } from './domain-available-error';
import { DomainAvailableResponse } from './domain-available-response';

/**
 * 
 * @export
 * @interface DomainAvailableBulkMixed
 */
export interface DomainAvailableBulkMixed {
    /**
     * Domain available response array
     * @type {Array<DomainAvailableResponse>}
     * @memberof DomainAvailableBulkMixed
     */
    'domains': Array<DomainAvailableResponse>;
    /**
     * Errors encountered while performing a domain available check
     * @type {Array<DomainAvailableError>}
     * @memberof DomainAvailableBulkMixed
     */
    'errors'?: Array<DomainAvailableError>;
}

