/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConsentDomainUpdate } from './consent-domain-update';

/**
 * 
 * @export
 * @interface DomainUpdate
 */
export interface DomainUpdate {
    /**
     * 
     * @type {ConsentDomainUpdate}
     * @memberof DomainUpdate
     */
    'consent'?: ConsentDomainUpdate;
    /**
     * Whether or not the domain contact details should be shown in the WHOIS
     * @type {boolean}
     * @memberof DomainUpdate
     */
    'exposeWhois'?: boolean;
    /**
     * Whether or not the domain should be locked to prevent transfers
     * @type {boolean}
     * @memberof DomainUpdate
     */
    'locked'?: boolean;
    /**
     * Fully-qualified domain names for Name Servers to associate with the domain
     * @type {Array<any>}
     * @memberof DomainUpdate
     */
    'nameServers'?: Array<any>;
    /**
     * Whether or not the domain should be configured to automatically renew
     * @type {boolean}
     * @memberof DomainUpdate
     */
    'renewAuto'?: boolean;
    /**
     * Reseller subaccount shopperid who can manage the domain
     * @type {string}
     * @memberof DomainUpdate
     */
    'subaccountId'?: string;
}

