/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConsentRenew } from './consent-renew';

/**
 * 
 * @export
 * @interface DomainRenewV2
 */
export interface DomainRenewV2 {
    /**
     * 
     * @type {ConsentRenew}
     * @memberof DomainRenewV2
     */
    'consent': ConsentRenew;
    /**
     * Current date when this domain will expire
     * @type {string}
     * @memberof DomainRenewV2
     */
    'expires': string;
    /**
     * Number of years to extend the Domain. Must not exceed maximum for TLD. When omitted, defaults to `period` specified during original purchase
     * @type {number}
     * @memberof DomainRenewV2
     */
    'period'?: number;
}

