/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Consent } from './consent';
import { Contact } from './contact';

/**
 * 
 * @export
 * @interface DomainPurchase
 */
export interface DomainPurchase {
    /**
     * 
     * @type {Consent}
     * @memberof DomainPurchase
     */
    'consent': Consent;
    /**
     * 
     * @type {Contact}
     * @memberof DomainPurchase
     */
    'contactAdmin'?: Contact;
    /**
     * 
     * @type {Contact}
     * @memberof DomainPurchase
     */
    'contactBilling'?: Contact;
    /**
     * 
     * @type {Contact}
     * @memberof DomainPurchase
     */
    'contactRegistrant'?: Contact;
    /**
     * 
     * @type {Contact}
     * @memberof DomainPurchase
     */
    'contactTech'?: Contact;
    /**
     * For internationalized domain names with non-ascii characters, the domain name is converted to punycode before format and pattern validation rules are checked
     * @type {string}
     * @memberof DomainPurchase
     */
    'domain': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DomainPurchase
     */
    'nameServers'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof DomainPurchase
     */
    'period'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DomainPurchase
     */
    'privacy'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DomainPurchase
     */
    'renewAuto'?: boolean;
}

