/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConsentV2 } from './consent-v2';
import { DomainContactsCreateV2 } from './domain-contacts-create-v2';

/**
 * 
 * @export
 * @interface DomainPurchaseV2
 */
export interface DomainPurchaseV2 {
    /**
     * 
     * @type {ConsentV2}
     * @memberof DomainPurchaseV2
     */
    'consent': ConsentV2;
    /**
     * 
     * @type {DomainContactsCreateV2}
     * @memberof DomainPurchaseV2
     */
    'contacts'?: DomainContactsCreateV2;
    /**
     * For internationalized domain names with non-ascii characters, the domain name is converted to punycode before format and pattern validation rules are checked
     * @type {string}
     * @memberof DomainPurchaseV2
     */
    'domain': string;
    /**
     * The domain eligibility data fields as specified by GET /v2/customers/{customerId}/domains/register/schema/{tld}
     * @type {object}
     * @memberof DomainPurchaseV2
     */
    'metadata'?: object;
    /**
     * 
     * @type {Array<string>}
     * @memberof DomainPurchaseV2
     */
    'nameServers'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof DomainPurchaseV2
     */
    'period'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DomainPurchaseV2
     */
    'privacy'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DomainPurchaseV2
     */
    'renewAuto'?: boolean;
}

