/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Contact } from './contact';

/**
 * 
 * @export
 * @interface DomainsContactsBulk
 */
export interface DomainsContactsBulk {
    /**
     * 
     * @type {Contact}
     * @memberof DomainsContactsBulk
     */
    'contactAdmin'?: Contact;
    /**
     * 
     * @type {Contact}
     * @memberof DomainsContactsBulk
     */
    'contactBilling'?: Contact;
    /**
     * 
     * @type {Contact}
     * @memberof DomainsContactsBulk
     */
    'contactPresence'?: Contact;
    /**
     * 
     * @type {Contact}
     * @memberof DomainsContactsBulk
     */
    'contactRegistrant'?: Contact;
    /**
     * 
     * @type {Contact}
     * @memberof DomainsContactsBulk
     */
    'contactTech'?: Contact;
    /**
     * An array of domain names to be validated against. Alternatively, you can specify the extracted tlds. However, full domain names are required if the tld is `uk`
     * @type {Array<string>}
     * @memberof DomainsContactsBulk
     */
    'domains': Array<string>;
    /**
     * Canadian Presence Requirement (CA)
     * @type {string}
     * @memberof DomainsContactsBulk
     */
    'entityType'?: DomainsContactsBulkEntityTypeEnum;
}

type DomainsContactsBulkEntityTypeEnum = 'ABORIGINAL' | 'ASSOCIATION' | 'CITIZEN' | 'CORPORATION' | 'EDUCATIONAL' | 'GOVERNMENT' | 'HOSPITAL' | 'INDIAN_BAND' | 'LEGAL_REPRESENTATIVE' | 'LIBRARY_ARCHIVE_MUSEUM' | 'MARK_REGISTERED' | 'MARK_TRADE' | 'PARTNERSHIP' | 'POLITICAL_PARTY' | 'RESIDENT_PERMANENT' | 'TRUST' | 'UNION'


