/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ErrorField
 */
export interface ErrorField {
    /**
     * Short identifier for the error, suitable for indicating the specific error within client code
     * @type {string}
     * @memberof ErrorField
     */
    'code': string;
    /**
     * Human-readable, English description of the problem with the contents of the field
     * @type {string}
     * @memberof ErrorField
     */
    'message'?: string;
    /**
     * <ul> <li style=\'margin-left: 12px;\'>JSONPath referring to a field containing an error</li> <strong style=\'margin-left: 12px;\'>OR</strong> <li style=\'margin-left: 12px;\'>JSONPath referring to a field that refers to an object containing an error, with more detail in `pathRelated`</li> </ul>
     * @type {string}
     * @memberof ErrorField
     */
    'path': string;
    /**
     * JSONPath referring to a field containing an error, which is referenced by `path`
     * @type {string}
     * @memberof ErrorField
     */
    'pathRelated'?: string;
}

