/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ErrorField } from './error-field';

/**
 * 
 * @export
 * @interface ErrorLimit
 */
export interface ErrorLimit {
    /**
     * Short identifier for the error, suitable for indicating the specific error within client code
     * @type {string}
     * @memberof ErrorLimit
     */
    'code': string;
    /**
     * List of the specific fields, and the errors found with their contents
     * @type {Array<ErrorField>}
     * @memberof ErrorLimit
     */
    'fields'?: Array<ErrorField>;
    /**
     * Human-readable, English description of the error
     * @type {string}
     * @memberof ErrorLimit
     */
    'message'?: string;
    /**
     * Number of seconds to wait before attempting a similar request
     * @type {number}
     * @memberof ErrorLimit
     */
    'retryAfterSec': number;
}

