/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ErrorFieldDomainContactsValidate } from './error-field-domain-contacts-validate';

/**
 * 
 * @export
 * @interface ErrorDomainContactsValidate
 */
export interface ErrorDomainContactsValidate {
    /**
     * Short identifier for the error, suitable for indicating the specific error within client code
     * @type {string}
     * @memberof ErrorDomainContactsValidate
     */
    'code': string;
    /**
     * List of the specific fields, and the errors found with their contents
     * @type {Array<ErrorFieldDomainContactsValidate>}
     * @memberof ErrorDomainContactsValidate
     */
    'fields'?: Array<ErrorFieldDomainContactsValidate>;
    /**
     * Human-readable, English description of the error
     * @type {string}
     * @memberof ErrorDomainContactsValidate
     */
    'message'?: string;
    /**
     * Stack trace indicating where the error occurred.<br/>NOTE: This attribute <strong>MAY</strong> be included for Development and Test environments. However, it <strong>MUST NOT</strong> be exposed from OTE nor Production systems
     * @type {Array<string>}
     * @memberof ErrorDomainContactsValidate
     */
    'stack'?: Array<string>;
}

