/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ErrorFieldDomainContactsValidate
 */
export interface ErrorFieldDomainContactsValidate {
    /**
     * Short identifier for the error, suitable for indicating the specific error within client code
     * @type {string}
     * @memberof ErrorFieldDomainContactsValidate
     */
    'code': string;
    /**
     * An array of domain names the error is for. If tlds are specified in the request, `domains` will contain tlds. For example, if `domains` in request is [\"test1.com\", \"test2.uk\", \"net\"], and the field is invalid for com and net, then one of the `fields` in response will have [\"test1.com\", \"net\"] as `domains`
     * @type {Array<string>}
     * @memberof ErrorFieldDomainContactsValidate
     */
    'domains': Array<string>;
    /**
     * Human-readable, English description of the problem with the contents of the field
     * @type {string}
     * @memberof ErrorFieldDomainContactsValidate
     */
    'message'?: string;
    /**
     * 1) JSONPath referring to the field within the data containing an error<br/>or<br/>2) JSONPath referring to an object containing an error
     * @type {string}
     * @memberof ErrorFieldDomainContactsValidate
     */
    'path': string;
    /**
     * JSONPath referring to the field on the object referenced by `path` containing an error
     * @type {string}
     * @memberof ErrorFieldDomainContactsValidate
     */
    'pathRelated'?: string;
}

