/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JsonDataType } from './json-data-type';

/**
 * 
 * @export
 * @interface JsonProperty
 */
export interface JsonProperty {
    /**
     * 
     * @type {string}
     * @memberof JsonProperty
     */
    'defaultValue'?: string;
    /**
     * 
     * @type {string}
     * @memberof JsonProperty
     */
    'format'?: string;
    /**
     * 
     * @type {Array<JsonDataType>}
     * @memberof JsonProperty
     */
    'items'?: Array<JsonDataType>;
    /**
     * 
     * @type {number}
     * @memberof JsonProperty
     */
    'maxItems'?: number;
    /**
     * 
     * @type {number}
     * @memberof JsonProperty
     */
    'maximum'?: number;
    /**
     * 
     * @type {number}
     * @memberof JsonProperty
     */
    'minItems'?: number;
    /**
     * 
     * @type {number}
     * @memberof JsonProperty
     */
    'minimum'?: number;
    /**
     * 
     * @type {string}
     * @memberof JsonProperty
     */
    'pattern'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof JsonProperty
     */
    'required': boolean;
    /**
     * 
     * @type {string}
     * @memberof JsonProperty
     */
    'type': string;
}

