/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JsonProperty } from './json-property';

/**
 * 
 * @export
 * @interface JsonSchema
 */
export interface JsonSchema {
    /**
     * 
     * @type {string}
     * @memberof JsonSchema
     */
    'id': string;
    /**
     * 
     * @type {Array<JsonSchema>}
     * @memberof JsonSchema
     */
    'models': Array<JsonSchema>;
    /**
     * 
     * @type {Array<JsonProperty>}
     * @memberof JsonSchema
     */
    'properties': Array<JsonProperty>;
    /**
     * 
     * @type {Array<string>}
     * @memberof JsonSchema
     */
    'required': Array<string>;
}

