/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LegalAgreement
 */
export interface LegalAgreement {
    /**
     * Title of the legal agreement
     * @type {string}
     * @memberof LegalAgreement
     */
    'title': string;
    /**
     * Unique identifier for the legal agreement
     * @type {string}
     * @memberof LegalAgreement
     */
    'agreementKey': string;
    /**
     * Contents of the legal agreement, suitable for embedding
     * @type {string}
     * @memberof LegalAgreement
     */
    'content': string;
    /**
     * URL to a page containing the legal agreement
     * @type {string}
     * @memberof LegalAgreement
     */
    'url'?: string;
}

