/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MaintenanceSystem
 */
export interface MaintenanceSystem {
    /**
     * The impact of the maintenance to the system<br/><ul><li><strong style=\'margin-left: 12px;\'>DELAYED</strong> - This response generally applies to systems where the request is queued up and processed once the system is back online.</li><li><strong style=\'margin-left: 12px;\'>DOWN</strong> - The system will be entirely offline; errors are expected.</li><li><strong style=\'margin-left: 12px;\'>NON_AUTHORITATIVE</strong> - This response generally applies to DOMAIN_CHECKS and DOMAIN_MANAGEMENT `system` values where a cached answer will be supplied.</li><li><strong style=\'margin-left: 12px;\'>PARTIAL</strong> - The system will experience partial feature outages; some errors are expected.</li></ul>
     * @type {Array<string>}
     * @memberof MaintenanceSystem
     */
    'impact': Array<MaintenanceSystemImpactEnum>;
    /**
     * The name of the system affected by the maintenance<br/><ul><li><strong style=\'margin-left: 12px;\'>DOMAIN_CHECKS</strong> - Refers to domain availability checks.</li><li><strong style=\'margin-left: 12px;\'>DOMAIN_MANAGEMENT</strong> - Refers to domain management options including various update options on the domain, contacts, records, etc.</li><li><strong style=\'margin-left: 12px;\'>DOMAIN_REGISTRATION</strong> - Refers to domain registrations, renewals, transfers.</li><li><strong style=\'margin-left: 12px;\'>DOMAIN_REGISTRATION_DATA</strong> - Refers to RDAP and WHOIS Service queries for domains.</li><li><strong style=\'margin-left: 12px;\'>DOMAIN_RESOLUTION</strong> - Refers to DNS resolution for domains.</li><li><strong style=\'margin-left: 12px;\'>RESELLER_ADMIN_PORTAL</strong> - Refers to Admin portals to manage the reseller account and settings.</li><li><strong style=\'margin-left: 12px;\'>RESELLER_STOREFRONT</strong> - Refers to the Reseller Storefront features (Standard and Custom).</li></ul>
     * @type {string}
     * @memberof MaintenanceSystem
     */
    'name': MaintenanceSystemNameEnum;
}

type MaintenanceSystemImpactEnum = 'DELAYED' | 'DOWN' | 'NON_AUTHORITATIVE' | 'PARTIAL'
type MaintenanceSystemNameEnum = 'DOMAIN_CHECKS' | 'DOMAIN_MANAGEMENT' | 'DOMAIN_REGISTRATION' | 'DOMAIN_REGISTRATION_DATA' | 'DOMAIN_RESOLUTION' | 'RESELLER_ADMIN_PORTAL' | 'RESELLER_STOREFRONT'


