/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RenewalDetails
 */
export interface RenewalDetails {
    /**
     * Currency in which the `price` is listed
     * @type {string}
     * @memberof RenewalDetails
     */
    'currency': string;
    /**
     * Price for the domain renewal excluding taxes or fees
     * @type {number}
     * @memberof RenewalDetails
     */
    'price': number;
    /**
     * Whether or not the domain is eligble for renewal based on status
     * @type {boolean}
     * @memberof RenewalDetails
     */
    'renewable'?: boolean;
}

