/*


All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TldSummary
 */
export interface TldSummary {
    /**
     * Name of the top-level domain
     * @type {string}
     * @memberof TldSummary
     */
    'name': string;
    /**
     * Type of the top-level domain
     * @type {string}
     * @memberof TldSummary
     */
    'type': TldSummaryTypeEnum;
}

type TldSummaryTypeEnum = 'COUNTRY_CODE' | 'GENERIC'


